create table households (id uuid primary key default gen_random_uuid(), nama text not null, created_by uuid references auth.users(id), created_at timestamptz default now());
create table memberships (user_id uuid references auth.users(id), household_id uuid references households(id) on delete cascade, role text check (role in ('admin','member')) default 'member', status text default 'active', primary key (user_id, household_id));
alter table households enable row level security;
alter table memberships enable row level security;
create policy "member baca rumahnya" on households for select using (exists (select 1 from memberships m where m.household_id = id and m.user_id = auth.uid() and m.status='active'));
create policy "user buat rumah" on households for insert with check (true);
create policy "admin update rumah" on households for update using (exists (select 1 from memberships m where m.household_id = id and m.user_id = auth.uid() and m.role='admin'));
create table tasks (id uuid primary key default gen_random_uuid(), household_id uuid references households(id) on delete cascade not null, judul text not null, deskripsi text default '', deadline date, prioritas text default 'normal', status text default 'todo' check (status in ('todo','done')), assignee_id uuid references auth.users(id), created_by uuid references auth.users(id), created_at timestamptz default now());
alter table tasks enable row level security;
create policy "scope rumah tasks" on tasks for all using (exists (select 1 from memberships m where m.household_id = tasks.household_id and m.user_id = auth.uid() and m.status='active')) with check (household_id is not null);
create table bills (id uuid primary key default gen_random_uuid(), household_id uuid references households(id) on delete cascade not null, nama text not null, nominal int not null check (nominal >= 0), jatuh_tempo date not null, status text default 'belum' check (status in ('belum','lunas')), bukti_url text, created_by uuid references auth.users(id));
alter table bills enable row level security;
create policy "scope rumah bills" on bills for all using (exists (select 1 from memberships m where m.household_id = bills.household_id and m.user_id = auth.uid())) with check (household_id is not null);
create table shopping_items (id uuid primary key default gen_random_uuid(), household_id uuid references households(id) on delete cascade not null, nama text not null, jumlah text default '1', catatan text default '', status text default 'perlu' check (status in ('perlu','dibeli')), created_by uuid references auth.users(id));
alter table shopping_items enable row level security;
create policy "scope rumah shopping" on shopping_items for all using (exists (select 1 from memberships m where m.household_id = shopping_items.household_id and m.user_id = auth.uid())) with check (household_id is not null);
create table schedules (id uuid primary key default gen_random_uuid(), household_id uuid references households(id) on delete cascade not null, judul text not null, mulai timestamptz not null, selesai timestamptz, lokasi text default '', created_by uuid references auth.users(id));
alter table schedules enable row level security;
create policy "scope rumah schedules" on schedules for all using (exists (select 1 from memberships m where m.household_id = schedules.household_id and m.user_id = auth.uid())) with check (household_id is not null);
create table reminders (id uuid primary key default gen_random_uuid(), household_id uuid references households(id) on delete cascade not null, ref_tipe text not null, ref_id uuid, waktu timestamptz not null, pengulangan text default 'sekali', target_user_id uuid references auth.users(id), aktif boolean default true);
alter table reminders enable row level security;
create policy "scope rumah reminders" on reminders for all using (exists (select 1 from memberships m where m.household_id = reminders.household_id and m.user_id = auth.uid())) with check (household_id is not null);
